version: '3.9'
services:
   db:
    container_name: db
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=map_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresadmin7
   web:
     container_name: web
     build: ./
     command: bash ./entrypoint.sh
     ports:
       - "8000:8000"
     expose:
       - 8000
     volumes:
       - ./app/static:/usr/src/app/webgis/static
       - ./app/media:/usr/src/app/webgis/media
     env_file:
       - ./.env
     depends_on:
       - db
volumes:
  postgres_data:

