version: '3.9'
services:
   db:
    container_name: db
    image: postgis/postgis
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=map_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresadmin7
   api:
     container_name: api
     build:
       context: ./
       dockerfile: Dockerfile
     command: bash ./entrypoint.sh
     ports:
       - "8000:8000"
     expose:
       - 8000
     volumes:
       - ./webgis/static:/usr/src/app/webgis/static
       - ./webgis/media:/usr/src/app/webgis/media
     env_file:
       - ./.env
     depends_on:
       - db
   web:
     container_name: web
     build:
       context: ./
       dockerfile: WebDockerfile
#     command: bash ./entrypointWeb.sh
     ports:
       - "8082:8080"
     depends_on:
       - api
volumes:
  postgres_data:

